apiVersion: v1
kind: Service
metadata:
  name: g-monitoring-app2-service
  namespace: dev-gan-app2-ns
  labels:
    name: g-monitoring-app2-service
    app: g-monitoring-app2-app
    project: g-monitoring-project
spec:
  ports:
    - name: main-container
      port: 8080
      targetPort: 8080
  selector:
    name: g-monitoring-app2-deployment